### ISSUE TITLE
Returns body if document is not scrollable

### ISSUE THREAD

**Issue by zcorpan** [mathiasbynens/document.scrollingElement#1]
See https://gist.github.com/dperini/ac3d921d6a08f10fd10e#comment-1419184

Since this script decides which element to return only once when first loaded, it is plausible that there isn't enough content in the document to cause scrolling when the script loads (depending on where the script is included).

I think something like this should more reliably tell you if the implementation complies with the spec in standards mode, regardless of the state of the document when the script runs:

``` js
var iframe = document.createElement('iframe');
iframe.style.height = '1px';
(document.body || document.documentElement).appendChild(iframe);
var d = iframe.contentWindow.document;
d.write('<!doctype html><div style="height:1000px">x</div>');
d.close();
var isCompliant = d.documentElement.scrollHeight > d.body.scrollHeight;
iframe.parentNode.removeChild(iframe);
```

The above only needs to run once, can happen anytime (in `head` works). No need to run it if you're in quirks mode.

If you want to support loading the polyfill in head or otherwise return the right thing when dynamic changes happen, you need to use a getter function that returns `documentElement` or `body` (depending on `isCompliant` and `document.compatMode`).

**Comment by mathiasbynens** [comment]
This shouldn’t be a problem as long as the script is placed near `</body>`, but the workaround seems straightforward enough. I’ll get it done.

**Comment by mathiasbynens** [comment]
Hmm, if we want to make the polyfill work in `<head>`, we need a different way to detect is the document is a `<frameset>` document.

``` js
var isFrameset = document.body && !/body/i.test(document.body.tagName);
```

…is `null` if `document.body` is `null`.

Any ideas, other than making the whole thing a getter as @zcorpan suggested or [waiting for `DOMContentLoaded`](https://github.com/dperini/ContentLoaded/blob/master/src/contentloaded.js) (which adds a lot of code)?

**Comment by mathiasbynens** [comment]
Any ideas, other than making the whole thing a getter as @zcorpan suggested or [waiting for `DOMContentLoaded`](https://github.com/dperini/ContentLoaded/blob/master/src/contentloaded.js) (which adds a lot of code)?
