### ISSUE TITLE
Failing frameset tests

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/document.scrollingElement#14]
Since merging #13, both frameset tests fail consistently. @zcorpan?

**Comment by zcorpan** [comment]
Maybe fixed by https://github.com/mathiasbynens/document.scrollingElement/commit/443c124c9c8db47cb7409855a27742d6dd8890e3

**Comment by mathiasbynens** [comment]
Fix confirmed. Thanks!
