### ISSUE TITLE
Remaining issues?

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/document.scrollingElement#16]
Quoting @RByers in https://github.com/w3ctag/spec-reviews/issues/51#issuecomment-93776653:

> We could argue that they (and anyone else like them) should use an iframe measurement hack (like the above polyfill - which by the way still has issues), or they should deprecate this public API. But that would take way more debate/effort than at least I'm willing to stomach.

Which issues are you talking about exactly?

**Comment by RByers** [comment]
I haven't looked into them at all but Boris raised a number of issues here: https://bugzilla.mozilla.org/show_bug.cgi?id=1153322#c4

**Comment by mathiasbynens** [comment]
That was filed as #9 and fixed soon after. Anything else?

**Comment by RByers** [comment]
Ah, sorry!  Wow the polyfill is much more involved now, sorry I missed that.  Thanks for pushing this!  It's useful to have the polyfill and hopefully the complexity of a correct polyfill helps justify why we need a browser API for this.
