### ISSUE TITLE
Returning 'null' in Standards Mode

### ISSUE THREAD

**Issue by tjni** [mathiasbynens/document.scrollingElement#22]
I work in a large SPA code base, in which (for better or worse) there are situations where both the html and body element have non-visible overflow. In these cases, the polyfill will return null. Is this the intended behavior even if my page is in standards mode?

**Comment by dperini** [comment]
Maybe I am missing the point.

Why would you bother with "scrolling" in Single Page Applications that have
non visible overflow both on the HTML and BODY elements (non-scrollable) ?

Anyway, as an answer to your question, in "Standard Mode", if the page is
long enough and overflows the browser visible area and the defaults value
(auto) for the CSS "overflow" property has not been changed, the
"scrollable" element should be the HTML element (I believe this is still
clearly written in some part of the specs but I don't have the link at
hand).


Diego



2017-02-02 10:35 GMT+01:00 Theodore Ni <notifications@github.com>:

**Comment by tjni** [comment]
Probably the less I guess about why this happens in my code base, the better. To be honest, I don't know a lot about how overflow values on the viewport affect the experience.

One place sets the overflow-y property on the body to scroll to prevent scrollbar showing and hiding from moving content around. Another sets overflow on the body to hidden to prevent scrolling when showing modals. Yet another sets the overflow-y property on html to auto (which apparently is not the default value) to achieve a temporary effect. Meanwhile, another piece of code is running on a timer to collect information from document.scrollingElement and finds that it is occasionally null. It's quite a hodgepodge. 

I found the part in the CSSOM View Module overview that backs up what you're saying.

> 1. If the {{Document}} is in <a>quirks mode</a>, follow these substeps:
>     1. If <a>the HTML <code>body</code> element</a> exists, and it does not have an associated <a>scrolling box</a>, return <a>the HTML <code>body</code> element</a> and abort these steps.
>     1. Return null and abort these steps.
> 1. If there is a root element, return the root element and abort these steps.
> 1. Return null.
> 
> Note: For non-conforming user agents that always use the <a>quirks mode</a> behavior for {{Element/scrollTop}}
> and {{Element/scrollLeft}}, the {{Document/scrollingElement}} attribute is expected to also always return
> <a>the HTML <code>body</code> element</a> (or null if it does not exist).

My interpretation is that checking whether the body has a scrolling box or not only happens in quirks mode. To sanity check, I looked into the built-in behavior in Firefox, which appears to apply this interpretation. On the other hand, Chrome always returns body whether in quirks mode or not, which could be how it interprets the note at the bottom.

If I'm not too off base, I can work on a PR that adjusts the code to match this behavior. Let me know what you think.

**Comment by dperini** [comment]
I believe you should consider Firefox as your reference browser and the
CSSOM specification for the scrolling behavior.

If you don't use "Quirks mode" the scrolling element should be the
"document.documentElement" and make and exception for browsers based on
Webkit.

Chrome/Safari have had this bug for years ...

Their developer teams promised several time to fix their behavior with the
BODY element being the default "scrolling element" but filed to do so as
many time as they promised a fix.

The Chrome team also forced any other browser vendor to implement an
useless property like "document.scrollingElement" saying that only having
that path will ensure they will fix the problem.

I see that the property "document.scrollingElement" have been implemented
at least two years ago but the problem persists and there are no evidence
they are working on a fix.

The last time I looked in to this was in 2015, here is a link with some
facts and other links:
https://dev.opera.com/articles/fixing-the-scrolltop-bug/


Diego



2017-02-02 19:27 GMT+01:00 Theodore Ni <notifications@github.com>:
