### ISSUE TITLE
Is there a reason this is a getter instead of a static value?

### ISSUE THREAD

**Issue by phistuck** [mathiasbynens/document.scrollingElement#3]
https://github.com/mathiasbynens/document.scrollingElement/blob/d1c287dfb1fcc928245827922dcb99e5b0880ef5/scrollingelement.js#L31

Why should it calculate it every time?
(I know there is some calculation running when the entire script runs, but you still calculate stuff in a getter)

Is it in case the page is morphed into a frameset page?

**Comment by mathiasbynens** [comment]
This is because the value of `document.body` can change. If the polyfill script is placed in the `<head>`, `document.body` is still `null` when the non-getter code executes.

Quick test case to demonstrate this:

``` html
<!DOCTYPE html>
<head><script>alert(document.body)</script>
<body><script>alert(document.body)</script>
```

URL: `data:text/html,<!DOCTYPE html><head><script>alert(document.body)</script><body><script>alert(document.body)</script>`

> Is it in case the page is morphed into a frameset page?

The current code would indeed account for that scenario as well (if such a thing is even possible — I honestly don’t know).

**Comment by phistuck** [comment]
But once this is settled (`body` is not null anymore), you can replace the getter with a static value.
I think this is the correct way, because you usually query and mess with `document.scrollingElement` during a scroll event. Doing as less as possible is preferred in this event, because it causes visible jank, especially in slower or older browsers.
In this case, performance should be prioritized over correctness in all of the edge cases (the morphed to frameset case).

**Comment by mathiasbynens** [comment]
> Doing as little as possible is preferred in this event, because it causes visible jank, especially in slower or older browsers.

In https://github.com/mathiasbynens/document.scrollingElement/blob/6c7d0258ffeaa3db400e7895bfe0c9458eb7b074/scrollingelement.js#L19-L28, what in particular causes “visible jank”?

Anyway, developers that want to avoid this can simply cache the result:

``` js
// In user code that is known to run after `DOMContentLoaded`:
var scrollingElement = document.scrollingElement;
// From here on out, use `scrollingElement` instead of `document.scrollingElement`
```

**Comment by phistuck** [comment]
Nothing specific (they add up), but it is more work (you access the DOM, you execute regular expressions) than a a trivial getter.

The whole purpose of a polyfill is not to change the code and do as you would normally do, which would probably be just `document.scrollingElement`.
