### ISSUE TITLE
In IE6/7/8 changes to the "activeElement" property does not ensure document is fully loaded

### ISSUE THREAD

**Issue by dperini** [mathiasbynens/document.scrollingElement#8]
On Internet Explorer, relying on the `propertychange` event for the `document.activeElement` property, to detect document is fully loaded, is a weak assumption.

That may be true for short static HTML, but it is not true for dynamic HTML when the page is served with chunked `Transfer-encoding` header.

For all browsers platforms I believe relying on the `DOMContentLoaded` event is better and is the right moment to do the check and set the `document.scrollingElement` to the correct element.

**Comment by dperini** [comment]
Here is the test in PHP, try it on your local server:

```
<!DOCTYPE html>
<html>
<head>
<title>Observing "document.activeElement" property changes on IE <= 8</title>
<script>
if (typeof document.attachEvent == 'object') {
        function changedActive(event) {
                if (event.propertyName == 'activeElement') {
                        document.detachEvent('onpropertychange', changedActive);
                        console.log(document.getElementsByTagName('div').length == 3 ? 'Success' : 'Failed');
                }
        }
        document.attachEvent('onpropertychange', changedActive);
}
</script>
</head>
<body>

<?php usleep(100000); flush(); ?><div>TEST</div>
<?php usleep(100000); flush(); ?><div>TEST</div>
<?php usleep(100000); flush(); ?><div>TEST</div>

</body>
</html>
```

this is an IE <= 8 only test.

**Comment by zcorpan** [comment]
It's not meant to detect the document is fully loaded. It's meant to detect that document.body is non-null. Why wait longer?

**Comment by dperini** [comment]
If this is only necessary to check "document.body" is not "null" then you are correct !

**Comment by zcorpan** [comment]
Great! Thanks for testing :)
